# Generated by Django 5.1.1 on 2025-03-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_userdata_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='email_visibility',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='instagram_visibility',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='whatsapp_visibility',
        ),
        migrations.AddField(
            model_name='settings',
            name='profile_visibility',
            field=models.CharField(choices=[('ALL', 'Visible to all UCL students'), ('FACULTY', 'Visible to everyone in the faculty'), ('DEPARTMENT', 'Visible to everyone in the faculty'), ('COURSE', 'Visible to everyone in the course'), ('PRIVATE', 'Only visible to me')], default='COURSE', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='instagram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
