# Generated by Django 5.1.7 on 2025-03-18 23:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_studentmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='instagram',
            field=models.CharField(blank=True, max_length=31, null=True, validators=[django.core.validators.RegexValidator(message='Must be valid username.', regex='^@?[a-zA-Z0-9._]{1,30}$')]),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='personal_email',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.RegexValidator(message='Must be a valid email address', regex='^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')]),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Must be valid phone number', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='studentID',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='Must be valid student ID.', regex='^[0-9]{8}$')]),
        ),
    ]
