# Generated by Django 5.1.1 on 2025-03-19 20:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('ucl_email', models.EmailField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Must be a valid UCL email ending in @ucl.ac.uk.', regex='^[a-zA-Z0-9._%+-]+@ucl\\.ac\\.uk$')])),
                ('student_number', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='Must be valid student ID.', regex='^[0-9]{8}$')])),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.departmentmodel')),
            ],
        ),
        migrations.AddField(
            model_name='departmentmodel',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.facultymodel'),
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ucl_email', models.EmailField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Must be a valid UCL email ending in @ucl.ac.uk.', regex='^[a-zA-Z0-9._%+-]+@ucl\\.ac\\.uk$')])),
                ('student_number', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='Must be valid student ID.', regex='^[0-9]{8}$')])),
                ('personal_email', models.EmailField(blank=True, max_length=150, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Must be a valid email address', regex='^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')])),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Must be valid phone number', regex='^\\+?1?\\d{9,15}$')])),
                ('instagram', models.CharField(blank=True, max_length=31, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Must be valid username.', regex='^@?[a-zA-Z0-9._]{1,30}$')])),
                ('discord', models.CharField(blank=True, max_length=32, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Must be valid discord username.', regex='^(?!.*\\.\\.)(?!.*\\.$)[a-z0-9._]{2,32}$')])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.coursemodel')),
            ],
        ),
        migrations.AddField(
            model_name='facultymodel',
            name='students',
            field=models.ManyToManyField(blank=True, to='App.studentmodel'),
        ),
        migrations.AddField(
            model_name='departmentmodel',
            name='students',
            field=models.ManyToManyField(blank=True, to='App.studentmodel'),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='students',
            field=models.ManyToManyField(blank=True, to='App.studentmodel'),
        ),
    ]
