# Generated by Django 5.1.1 on 2025-03-26 10:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_department_faculty_alter_department_students'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='Options',
        ),
    ]
