# Generated by Django 5.1.1 on 2025-03-26 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_userdata_profile_visibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='discord',
            field=models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Discord username. ', regex='^([a-zA-Z0-9_\\.]{2,32})(#[0-9]{4})?$')]),
        ),
        migrations.AddField(
            model_name='userdata',
            name='name',
            field=models.CharField(default='John Doe', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='instagram',
            field=models.CharField(blank=True, max_length=31, null=True, validators=[django.core.validators.RegexValidator(message='Must be valid Instagram username.', regex='^@?[a-zA-Z0-9._]{1,30}$')]),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Must be valid phone number', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
