# Generated by Django 5.1.1 on 2025-03-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_userdata_discord_userdata_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
